### ISSUE TITLE
site cassé

### ISSUE THREAD

**Issue by JLuc** [DavidBruant/davidbruant.github.io#4]
https://davidbruant.github.io/writings/libre-et-design-autres-pistes-de-reflexion et toutes les autres pages consultées depuis https://davidbruant.github.io/writings/ sont cassées

**Comment by DavidBruant** [comment]
je crois que j'ai réussi à réparer le style
https://davidbruant.github.io/writings/
https://davidbruant.github.io/2017/02/12/libre-et-design-autres-pistes-de-reflexion.html
